name = input('What is your name: ')
print('Your name is ',name)
print(name,'Solve the quadratic equation by inputting the value :')
print('Input Value for a')
a = int(input())
print('Input Value for b')
b = int(input())
print('Input Value for c')
c = int(input())
x = (-b + 4 * a * c)/ (2 * a)
print('The Value of x is',x)
